### ISSUE TITLE
CSS实现多行文本溢出省略号

### ISSUE THREAD

**Issue by KamyoChae** [KamyoChae/Blog-on-github#52]
# CSS实现多行文本溢出省略号
tags: [CSS, webApp]
---
大家可能都知道如何利用css实现单行文本溢出省略号的实现方式，但实际工作中可能还会遇到一种需求：实现多行文本溢出部分转变成省略号。这篇文章简单描述一下如何实现多行溢出。

单行文本溢出部分转省略号的css写法
```css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

## WebKit浏览器或移动端的页面实现多行溢出省略
在WebKit浏览器或移动端（绝大部分是WebKit内核的浏览器）的页面实现比较简单，可以直接使用WebKit的CSS扩展属性(WebKit是私有属性)-webkit-line-clamp ；注意：这是一个 不规范的属性（unsupported WebKit property），它没有出现在 CSS 规范草案中。

-webkit-line-clamp用来限制在一个块元素显示的文本的行数。 为了实现该效果，它需要组合其他的WebKit属性。查看 text-overflow 属性文档：http://www.css88.com/book/css/webkit/text/line-clamp.htm

常见结合属性：

- display: -webkit-box; 必须结合的属性 ，将对象作为弹性伸缩盒子模型显示 。
- -webkit-box-orient 必须结合的属性 ，设置或检索伸缩盒对象的子元素的排列方式 。
- text-overflow: ellipsis;，可以用来多行文本的情况下，用省略号“…”隐藏超出范围的文本 。

查看 `text-overflow` 属性文档：http://www.css88.com/book/css/properties/user-interface/text-overflow.htm

代码实现方式
```css
overflow : hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 2;
-webkit-box-orient: vertical;
```
这个属性比较合适WebKit浏览器或移动端（绝大部分是WebKit内核的）浏览器。

具体例子可以查看http://www.css88.com/book/css/webkit/text/line-clamp.htm

## 跨浏览器兼容的方案
比较靠谱简单的做法就是设置相对定位的容器高度，用包含省略号(…)的元素模拟实现；

例如：
```css
p {
position:relative;
line-height:1.4em;
/* 3 times the line-height to show 3 lines */
height:4.2em;
overflow:hidden;
}
p::after {
content:"...";
font-weight:bold;
position:absolute;
bottom:0;
right:0;
padding:0 20px 1px 45px;
background:url(http://newimg88.b0.upaiyun.com/newimg88/2014/09/ellipsis_bg.png) repeat-y;
}
```
这里注意几点：

1. height高度真好是line-height的3倍；
1. 结束的省略好用了半透明的png做了减淡的效果，或者设置背景颜色；
1. IE6-7不显示content内容，所以要兼容IE6-7可以是在内容中加入一个标签，比如用<span class="line-clamp">...</span>去模拟；
1. 要支持IE8，需要将::after替换成:after；

本文参考文章（http://www.css88.com/archives/5206）
